### ISSUE TITLE
Load stero wave files (mix to mono)

### ISSUE THREAD

**Issue by naught101** [swesterfeld/spectmorph#14]
Most of my samples in my library are stereo. I would love be able to use them without having to mix them to mono manually. It would be nice if spectmorph could load them and mix them to mono and use them directly.

**Comment by swesterfeld** [comment]
Yes, I totally agree that SpectMorph should do something smarter if you try to import a stereo file. My suggestion would be that if you try to load a stereo file, SpectMorph would open a dialog with four options:

 * use left channel only
 * use right channel only
 * downmix
 * don't load
