### ISSUE TITLE
Instrument editor: Center start play marker

### ISSUE THREAD

**Issue by HiSven** [swesterfeld/spectmorph#22]
Is it possible to center the "start play marker" while dragging the hzoom? It is easier to edit the exact begin of a sample if the start marker is always visible in the center of the screen.

**Comment by swesterfeld** [comment]
Well, the question would be which marker should be centered on the screen. There is a marker for the end and possibly two loop point markers. So to do this, we could maintain a marker selection that would keep track of the last marker that you moved and keep this one centered. Not sure if that would be good from a usability point of view.

An alternative would be to allow clicking on the sample view and dragging it upwards/downwards for hzoom in/out. That way the point you clicked on would remain inside the magnified part of the sample.

**Comment by HiSven** [comment]
Thanks for your quick answer!

There are several options:

1. the most- leftside marker
2. Zoom by clicking and dragging (not the best option because of the long vertical way for the mouse)
3. You click inside the wave, and a vertical line appears. This one is the focal point of the zoom which is centered.
