### ISSUE TITLE
sminstbuilder is not python3

### ISSUE THREAD

**Issue by dvzrv** [swesterfeld/spectmorph#6]
Hi! I maintain spectmorph on Arch Linux and we're about to [drop python2, as it's EOL](https://pythonclock.org/).
Please update [sminstbuilder](https://github.com/swesterfeld/spectmorph/blob/master/tools/sminstbuilder.in) to be python3 and release a new version of spectmorph.

In the meantime I'll have to drop support for the script (or best remove it) from the package.

Thank you!

**Comment by swesterfeld** [comment]
Right. I'm working on the python3 ports now, its not just sminstbuilder but also other scripts (i.e. needed by make check).

As for a release, I'll wait a bit until there are some more changes, as each release is quite a bit of work.

**Comment by swesterfeld** [comment]
Ok, all code is python3 ported, so I close this. I keep in mind you need a release, too.

**Comment by swesterfeld** [comment]
It has been fixed in this commit:

 * https://github.com/swesterfeld/spectmorph/commit/13ad0087f159850d9dd6650c3d3733a6e0199968

which is available since 0.5.1.
